### ISSUE TITLE
Support custom whisper models

### ISSUE THREAD

**Issue by kcoderhtml** [rhasspy/wyoming-faster-whisper#10]
I think this would make the project much more versatile and future-proof. An example of a custom model would be https://github.com/huggingface/distil-whisper, which is up to 6 times faster than base whisper.

**Comment by AnkushMalaker** [comment]
I initially added distil-whisper support and then followed up by same realization.  The faster-whisper backend can handle different models, allowing huggingface downloads instead of the current restricted set of downloads would be nice. 
Initially the model specified goes through an FasterWhisperModel enum which sets the initial limitation. 

Fork here: https://github.com/AnkushMalaker/wyoming-distil-whisper
I added other huggingface models functionality but that isn't in the scope of this repo, so I haven't made a PR yet.

But if you want to try out the distil-whisper-medium.en, I have a docker image here that you can try
`docker run --gpus all --network='host' -d ankushm8/wyoming-distil-whisper:gpu-medium.en --device cuda`

**Comment by yurgh** [comment]
Thumbs up for the possibility of using a different model. The speech-to-text for my native language, norwegian, is completely useless with the available options. I can convert a model to ct2 and put it in the data directory, but it's unfortunately not possible to run it.

**Comment by cociweb** [comment]
In my customized version, I've tried to avoid adding more dependencies and give support for a simple download from a specific remote folder (avoid to use git/or equivalent hf solutions.)
For an increased security purpose I'm using a pre-generated hash.json (but it also working without it)
You are also able to select the model from the frontend of the addon.

It is also very handy if you store your model privately.

Since ha/ha-os does not support GPU/cuda acceleration then I've made a standalone version too. 

you can grab it [here](https://github.com/cociweb/custom_whisper).

Since I've tried to stick As close to the original code as possible, then I have a serious issue in the fork: If the path is incorrect and one of the required file does not exist, then it turns into a bootloop: It tries to restart again an again. So please be cautious!

Let me highlight that custom model is very important for any non-english speaker users, since the quality of the original openai multilang models are incredibly creapy. Fine tuned models are a must have....
@synesthesiam can you please give it a try? Is it worth a PR?

**Comment by ser** [comment]
I have just written a simple wyoming connector to Whisper API, so you can now easily deploy many more models utilising Whisper.cpp:

https://github.com/ser/wyoming-whisper-api-client

**Comment by synesthesiam** [comment]
Version 2.0.0 allows passing in a model directory or HuggingFace model ID to `--model` (see: https://github.com/rhasspy/wyoming-faster-whisper/releases/tag/v2.0.0)
