### ISSUE TITLE
Build docker image based on version 1.1.0

### ISSUE THREAD

**Issue by sebastian-bugajny** [rhasspy/wyoming-faster-whisper#20]
Is there a change to build fresh docker image based on version 1.1.0. The latest one available on docker hub based on version 1.0.1

**Comment by mackowskim** [comment]
I'd double that. Please update image.

**Comment by ChiefJReloaded** [comment]
I would go a step further and say there needs to be a way for releases to happen semi-automated, be it Docker Images, PyPI or Github releases. Upstream devs are affected by this as well, e.g. [linuxserver/docker-faster-whisper](https://github.com/linuxserver/docker-faster-whisper), because they rely on published packages or querys to the Github-API for release information.

**Comment by synesthesiam** [comment]
Docker image has been uploaded to 2.0.0 (see: https://github.com/rhasspy/wyoming-faster-whisper/releases/tag/v2.0.0)
